SELECT TOD.CL_ORDER_ID AS "Order Id",
       TBO.CL_ENTERED_DATETIME AS "Order Entry Time",
       TBO.CL_ENTERED_BY AS "Entered By",
       TBO.CL_COUNTERPARTY_CODE AS "Cp View Code",
       (SELECT fDESCRIPTION FROM COUNTERPARTY CP,ALT_COUNTERPARTY_ID ACP 
        WHERE CP.COUNTERPARTY_ID=ACP.COUNTERPARTY_ID
        AND ACP.ALTERNATE_TYPE='VIEW'
        AND CP.COUNTERPARTY_ID=TBO.CL_COUNTERPARTY_ID) AS "Cp Description",
       CASE
       WHEN TBO.CL_BUY_SELL = 'B' THEN
            'Buy'
       ELSE
            'Sell'
       END AS 'Buy/Sell',
       TBO.CL_INSTRUMENT_CODE AS "Stock Code",     
       (SELECT DESCRIPTION FROM STB_INSTRUMENT WHERE INSTRUMENT_ID=TBO.CL_INSTRUMENT_CODE) AS "Stock Description",
       TBO.MARKET_ID AS "Market Id",
       (select SM.DESCRIPTION from STB_MARKET SM WHERE SM.MARKET_ID=TBO.MARKET_ID) AS "Market Description",
       TBO.CL_QUANTITY AS "Total Quantity",       
       TOD.CL_QUANTITY_FILLED AS "Executed Quantity",
       TOD.CL_GROSS_AVG_PRICE AS "Average Price",
       TOD.CL_QUANTITY_REMAINING AS "Quantity Remaining"
  FROM TB_ORDER TBO, TB_ORDER_DETAIL TOD, TB_CURRENT_ORDER TCO
 WHERE TBO.CL_ORDER_ID = TOD.CL_ORDER_ID
   AND TBO.CL_ORDER_ID = TCO.CL_ORDER_ID
   AND TBO.CL_VERSION = TCO.CL_VERSION
   AND (TBO.CL_ENTERED_BY = 'DMA' OR TBO.CL_ENTERED_BY like '%_PT')
   AND TBO.CL_ENTERED_DATETIME > '20080501' 
   AND TBO.CL_ENTERED_DATETIME < '20080601'   
ORDER BY TBO.CL_ENTERED_BY