-- currently displays all the active and closed shifts, when the user navigates to home page
--101-Active, 102-Inactive and 103-Closed
SELECT SHFTDEF.SHIFT_ID,
	SHFTDEF.ORG_ID,
	SHFTDEF.ORG_UNIT_ID,
	SHFTDEF.SHIFT_SCHED_LKUP_ID,
	SHFTLKUP.FIELD_NAME,
	SHFTLKUP.FIELD_VALUE,
	SHFTLKUP.DESCR,
	SHFTDEF.START_DATE,
	SHFTDEF.DUR_LKUP_ID,
	DURLKUP.FIELD_NAME,
	DURLKUP.FIELD_VALUE,
	DURLKUP.DESCR,
	SHFTDEF.PROFESSION_LKUP_ID,
	PROFLKUP.FIELD_NAME,
	PROFLKUP.FIELD_VALUE,
	PROFLKUP.DESCR,
	SHFTDEF.SPECIALTY_ID,
	SPLTY.SPECIALTY_NAME,
	SPLTY.DESCR,
	SHFTDEF.PAY_RATE,
	SHFTDEF.SHIFT_COUNT,
	SHFTDEF.DESCR,
	SHFTDEF.START_TIME,
	SHFTDEF.END_TIME,
	SHFTDEF."position",
	SHFTDEF.SHIFT_TYPE_LKUP_ID,
	SHFTTYPLKUP.FIELD_NAME,
	SHFTTYPLKUP.FIELD_VALUE,
	SHFTTYPLKUP.DESCR,
	SHFTDEF.PAY_FREQ_LKUP_ID,
	PAYFREQPLKUP.FIELD_NAME,
	PAYFREQPLKUP.FIELD_VALUE,
	PAYFREQPLKUP.DESCR,
	SHFTDEF.SHIFT_MON,
	SHFTDEF.SHIFT_TUE,
	SHFTDEF.SHIFT_WED,
	SHFTDEF.SHIFT_THU,
	SHFTDEF.SHIFT_FRI,
	SHFTDEF.SHIFT_SAT,
	SHFTDEF.SHIFT_SUN,
	SHFTDEF.END_DATE,
	SHFTDEF.SHIFT_STATUS_LKUP_ID,
	SHFTSTATLKUP.FIELD_NAME,
	SHFTSTATLKUP.FIELD_VALUE,
	SHFTSTATLKUP.DESCR
FROM EQ.SHIFT_DEFN SHFTDEF
LEFT JOIN EQ.LOOKUP SHFTLKUP ON SHFTDEF.SHIFT_SCHED_LKUP_ID = SHFTLKUP.LOOKUP_ID
LEFT JOIN EQ.LOOKUP DURLKUP ON SHFTDEF.DUR_LKUP_ID = DURLKUP.LOOKUP_ID
LEFT JOIN EQ.LOOKUP PROFLKUP ON SHFTDEF.PROFESSION_LKUP_ID = PROFLKUP.LOOKUP_ID
LEFT JOIN EQ.SPECIALTY SPLTY ON SHFTDEF.SPECIALTY_ID = SPLTY.SPECIALTY_ID
LEFT JOIN EQ.LOOKUP SHFTTYPLKUP ON SHFTDEF.SHIFT_TYPE_LKUP_ID = SHFTTYPLKUP.LOOKUP_ID
LEFT JOIN EQ.LOOKUP PAYFREQPLKUP ON SHFTDEF.PAY_FREQ_LKUP_ID = PAYFREQPLKUP.LOOKUP_ID
LEFT JOIN EQ.LOOKUP SHFTSTATLKUP ON SHFTDEF.SHIFT_STATUS_LKUP_ID = SHFTSTATLKUP.LOOKUP_ID
WHERE SHIFT_STATUS_LKUP_ID in (101)
	AND SHIFT_ID in (146)
--and start_date = '2022-12-27'

-- Table SHIFT_APPLIED:when the user applies for a shift this table stores the information
-- in regard to the shift approval by reviewer. Status can be either Pending, Approved and
-- rejected. Also contains the reviewer info.
SELECT SHFTAPP.SHIFT_APPLIED_ID,
	SHFTAPP.USER_ID,
	SHFTUSR.USER_NAME,
	SHFTAPP.SHIFT_ID,
	SHFTAPP.SHIFT_APPLY_STATUS_LKUP_ID,
	APPLYLKUP.FIELD_NAME as LKUP_NAME,
	APPLYLKUP.FIELD_VALUE as LKUP_VALUE,
	APPLYLKUP.DESCR as LKUP_DESCR,
	SHFTAPP.REVIEWED_USER_ID,
	SHFTUSR1.USER_NAME as reviewed_user_name,
	SHFTAPP.COMMENTS
FROM EQ.SHIFT_APPLIED SHFTAPP
LEFT JOIN EQ.MYSHIFT_USER SHFTUSR ON SHFTAPP.USER_ID = SHFTUSR.USER_ID
LEFT JOIN EQ.LOOKUP APPLYLKUP ON SHFTAPP.SHIFT_APPLY_STATUS_LKUP_ID = APPLYLKUP.LOOKUP_ID
LEFT JOIN EQ.MYSHIFT_USER SHFTUSR1 ON SHFTAPP.REVIEWED_USER_ID = SHFTUSR1.USER_ID
WHERE SHFTAPP.USER_ID in (139)

-- Table SHIFT_BYDATE : Displays all records for each day based on shift schedule, 
-- duration and shift type
SELECT SHIFT_BYDATE_ID,
	SHIFT_ID,
	SHIFT_DATE,
	CREATE_DT,
	CREATEBY_ID,
	UPDATE_DT,
	UPDATEBY_ID
FROM EQ.SHIFT_BYDATE
WHERE SHIFT_ID in (146)

--Table SHIFT_SWAP : Contains inforfmaton about the user who initiated swap, to which user/s
-- swap is sent, reason for swap and who approved the swap request
SELECT SHFTSWP.SHIFT_SWAP_ID,
	SHFTSWP.SHIFT_USER_ID,
	SHFTUSR.USER_NAME AS SHIFT_USER_NAME,
	SHFTSWP.SHIFT_BYDATE_ID,
	SHFTBYDT.SHIFT_ID,
	SHFTSWP.SWAPTO_USER_ID,
	SWPTOUSR.USER_NAME AS SWAPTO_USER_NAME,
	SHFTSWP.SWAPTO_USER_STATUS,
	SHFTSWP.SWAP_REASON,
	SHFTSWP.SWAP_STATUS,
	SHFTSWP.APPROVED_MANAGER_ID,
	MGRUSR.USER_NAME AS APPROVED_MANGER_NAME
FROM EQ.SHIFT_SWAP SHFTSWP
LEFT JOIN EQ.MYSHIFT_USER SHFTUSR ON SHFTSWP.SHIFT_USER_ID = SHFTUSR.USER_ID
LEFT JOIN EQ.SHIFT_BYDATE SHFTBYDT ON SHFTSWP.SHIFT_BYDATE_ID = SHFTBYDT.SHIFT_BYDATE_ID
LEFT JOIN EQ.MYSHIFT_USER SWPTOUSR ON SHFTSWP.SWAPTO_USER_ID = SWPTOUSR.USER_ID
LEFT JOIN EQ.MYSHIFT_USER MGRUSR ON SHFTSWP.SWAPTO_USER_ID = MGRUSR.USER_ID
where 
SHFTBYDT.SHIFT_ID=110
AND
SHFTSWP.SHIFT_USER_ID = 87

--Table SHIFT_WORKED : Contains the information in regard to hours worked and payment.
SELECT SHFTWRKD.SHIFT_WORKED_ID,
	SHFTWRKD.SHIFT_BYDATE_ID,
	SHFTBYDT.SHIFT_ID,
	SHFTWRKD.USER_ID,
	SHFTUSR.USER_NAME AS USER_NAME,
	SHFTWRKD.SEQ_NBR,
	SHFTWRKD.SHIFT_WORK_STATUS_LKUP_ID,
	WRKSTATLKUP.FIELD_NAME AS STATUS_LKUP_NAME,
	WRKSTATLKUP.FIELD_VALUE AS STATUS_LKUP_VALUE,
	WRKSTATLKUP.DESCR AS STATUS_DESCR,
	SHFTWRKD.CHECKIN_TIME,
	SHFTWRKD.CHECKOUT_TIME,
	SHFTWRKD.HRS_WORKED,
	SHFTWRKD.PAY_RATE,
	SHFTWRKD.PAY_FREQ_LKUP_ID,
	PYFRQLKUP.FIELD_NAME AS PAY_FREQ_LKUP_NAME,
	PYFRQLKUP.FIELD_VALUE AS PAY_FREQ_LKUP_VALUE,
	PYFRQLKUP.DESCR AS PAY_FREQ_DESCR,
	SHFTWRKD.PAY_AMOUNT,
	SHFTWRKD.PAY_STATUS_FLAG,
	SHFTWRKD.COMMENTS
FROM EQ.SHIFT_WORKED SHFTWRKD
LEFT JOIN EQ.SHIFT_BYDATE SHFTBYDT ON SHFTWRKD.SHIFT_BYDATE_ID = SHFTBYDT.SHIFT_BYDATE_ID
LEFT JOIN EQ.MYSHIFT_USER SHFTUSR ON SHFTWRKD.USER_ID = SHFTUSR.USER_ID
LEFT JOIN EQ.LOOKUP WRKSTATLKUP ON SHFTWRKD.SHIFT_WORK_STATUS_LKUP_ID = WRKSTATLKUP.LOOKUP_ID
LEFT JOIN EQ.LOOKUP PYFRQLKUP ON SHFTWRKD.PAY_FREQ_LKUP_ID = PYFRQLKUP.LOOKUP_ID
	
SELECT swap_accept_id, swap_id, receiver_user_id, swap_recv_status_lkup_id, createby_id, create_dt, updateby_id, update_dt, status_update_id, status_update_dt, receiver_accept_dt
	FROM eq.swap_accept;

SELECT swap_receiver_id, swap_id, receiver_user_id, swap_recv_status_lkup_id, createby_id, create_dt, updateby_id, update_dt
	FROM eq.swap_receiver;

SELECT swap_id, swap_user_id, shift_date_id, shift_id, request_date, swap_status_lkup_id, swap_reason_lkup_id, swap_reason, create_dt, createby_id, update_dt, updateby_id
	FROM eq.swap_request;

SELECT unit_id, unit_name, descr, isactive, create_dt, create_by, updte_dt, update_by
	FROM eq.unit;

SELECT user_role_id, user_id, role_id, org_id, create_dt, create_by, update_dt, update_by
	FROM eq.user_role;

SELECT shift_applied_id, user_id, shift_id, shift_apply_status_lkup_id, create_dt, create_by, update_dt, update_by, update_user_id
	FROM eq.xx_shift_apply;	