-- To check complete profile details for a specific user. Can also check for multiple users
-- by replacing the id with subquery in the where condition. Or else can comment the the
-- where condition(WHERE N1.USER_ID in (139)) to check for all users.
SELECT N1.*,
	N2.SPCLTY_LKUPID_LIST,
	N2.SPCLTY_NAME_LIST,
	N2.SPCLTY_DESCR_LIST,
	N3.CERT_ID_LIST,
	N3.CERT_NAME_LIST,
	N3.CERT_DESCR_LIST,
	N4.EDU_ID_LIST,
	N4.EDU_DEGREE_LIST,
	N4.EDU_SCHL_LIST,
	N4.EDU_CITY_LIST,
	N4.EDU_STATE_LIST,
	N4.EDU_ZIP_LIST,
	N4.EDU_STRTDT_LIST,
	N4.EDU_GRADDT_LIST,
	N4.EDU_CNTRY_LIST,
	N5.EMR_LKUPID_LIST,
	N5.EMR_NAME_LIST,
	N5.EMR_VAL_LIST,
	N5.EMR_DESCR_LIST,
	N6.EXP_STRTDT_LIST,
	N6.EXP_TITLE_LIST,
	N6.EXP_EMPTYP_LIST,
	N6.EXP_EMPTYPNAME_LIST,
	N6.EXP_EMPTYPVAL_LIST,
	N6.EXP_EMPTYPDESCR_LIST,
	N6.EXP_FCLTYNAME_LIST,
	N6.EXP_FCLTYTYP_LIST,
	N6.EXP_FCLTYLOC_LIST,
	N6.EXP_FCLTYUNT_LIST,
	N6.EXP_FCLTYSPLTY_LIST,
	N6.EXP_CHRG_LIST,
	N6.EXP_SHFTTYP_LIST,
	N6.EXP_SHFTTYPNAME_LIST,
	N6.EXP_SHFTTYPVAL_LIST,
	N6.EXP_SHFTTYPDESCR_LIST,
	N6.EXP_CURNTWRKNG_LIST,
	N6.EXP_HRSWK_LIST,
	N6.EXP_SPLTY_LIST,
	N6.EXP_SUPVR_LIST,
	N6.EXP_DESCR_LIST,
	N7.JBTYP_LKUPID_LIST,
	N7.JBTYP_NAME_LIST,
	N7.JBTYP_VAL_LIST,
	N7.JBTYP_DESCR_LIST,
	N8.LICID_LST,
	N8.LIC_ISSU_STAT_LST,
	N8.LICNUM_LST,
	N8.LICEXP_LST,
	N8.LIC_ISCOMPCT_LST,
	N8.LICAWSKY_LST,
	N8.LIC_VERFY_LST,
	N8.LIC_LKUP_LST,
	N8.LIC_LKUP_NAME_LST,
	N8.LIC_LKUP_VAL_LST,
	N8.LIC_LKUP_DESCR_LST,
	N8.LIC_TYP_LST,
	N8.LIC_DESCR_LST,
	N8.LIC_ACTV_LST,
	N9.VACC_LST,
	N10.REF_NAME_LST,
	N10.REF_POS_LST,
	N10.REF_PHN_LST,
	N10.REF_EMAIL_LST,
	N10.REF_RLTN_LST,
	N10.REF_FCLTNAM_LST,
	N10.REF_STRTDT_LST,
	N10.REF_ENDDT_LST,
	N11.CNTDUR_LKUPID_LST,
	N11.CNTDUR_LKUPNM_LST,
	N11.CNTDUR_LKUPVAL_LST,
	N11.CNTDUR_LKUPDESC_LST,
	N12.SHFTSHD_LKUPID_LST,
	N12.SHFTSHD_LKUPNM_LST,
	N12.SHFTSHD_LKUPVAL_LST,
	N12.SHFTSHD_LKUPDESC_LST,
	N13.SHFTTYP_LKUPID_LST,
	N13.SHFTTYP_LKUPNM_LST,
	N13.SHFTTYP_LKUPVAL_LST,
	N13.SHFTTYP_LKUPDESC_LST,
	N14.WRKHRS_LKUPID_LST,
	N14.WRKHRS_LKUPNM_LST,
	N14.WRKHRS_LKUPVAL_LST,
	N14.WRKHRS_LKUPDESC_LST	
FROM
	(SELECT SHFTUSR.USER_ID,
			SHFTUSR.USER_NAME,
			SHFTUSR.FIRST_NAME,
			SHFTUSR.LAST_NAME,
			SHFTUSR.ORIG_ID,
			SHFTUSR.PHONE_NBR,
			SHFTUSR.TERMS_ACCEPTED,
			SHFTUSR.CREATE_BY,
			SHFTUSR.USER_TYPE_LKUP_ID,
			CASE
			WHEN SHFTUSR.USER_TYPE_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_NAME
				FROM EQ.LOOKUP USRLKUP
				WHERE USRLKUP.LOOKUP_ID = SHFTUSR.USER_TYPE_LKUP_ID)
			END AS USR_LKUP_TYPE,
			CASE
			WHEN SHFTUSR.HEARUS_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_VALUE
				FROM EQ.LOOKUP USRLKUP
				WHERE USRLKUP.LOOKUP_ID = SHFTUSR.USER_TYPE_LKUP_ID)
			END AS USR_LKUP_VALUE,
			CASE
			WHEN SHFTUSR.HEARUS_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT DESCR
				FROM EQ.LOOKUP USRLKUP
				WHERE USRLKUP.LOOKUP_ID = SHFTUSR.USER_TYPE_LKUP_ID)
			END AS USR_LKUP_DESCR,
			SHFTUSR.HEARUS_LKUP_ID,
			CASE
			WHEN SHFTUSR.HEARUS_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_NAME
				FROM EQ.LOOKUP HRLKUP
				WHERE HRLKUP.LOOKUP_ID = SHFTUSR.HEARUS_LKUP_ID)
			END AS HEARUS_LKUP_TYPE,
			CASE
			WHEN SHFTUSR.HEARUS_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_VALUE
				FROM EQ.LOOKUP HRLKUP
				WHERE HRLKUP.LOOKUP_ID = SHFTUSR.HEARUS_LKUP_ID)
			END AS HEARUS_LKUP_VALUE,
			CASE
			WHEN SHFTUSR.HEARUS_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT DESCR
				FROM EQ.LOOKUP HRLKUP
				WHERE HRLKUP.LOOKUP_ID = SHFTUSR.HEARUS_LKUP_ID)
			END AS HEARUS_LKUP_DESC,
			SHFTUSR.PROFESSION_LKUP_ID,
			CASE
			WHEN SHFTUSR.PROFESSION_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_NAME
				FROM EQ.LOOKUP PROFLKUP
				WHERE PROFLKUP.LOOKUP_ID = SHFTUSR.PROFESSION_LKUP_ID)
			END AS PROF_LKUP_TYPE,
			CASE
			WHEN SHFTUSR.PROFESSION_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_VALUE
				FROM EQ.LOOKUP PROFLKUP
				WHERE PROFLKUP.LOOKUP_ID = SHFTUSR.PROFESSION_LKUP_ID)
			END AS PROF_LKUP_VALUE,
			CASE
			WHEN SHFTUSR.PROFESSION_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT DESCR
				FROM EQ.LOOKUP PROFLKUP
				WHERE PROFLKUP.LOOKUP_ID = SHFTUSR.PROFESSION_LKUP_ID)
			END AS PROF_LKUP_DESCR,
			SHFTUSR.PROFILEPIC_AWS_KEY,
			PRFL.WORKAREA_LKUP_ID,
			CASE
			WHEN PRFL.WORKAREA_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_NAME
				FROM EQ.LOOKUP WRKLKUP
				WHERE WRKLKUP.LOOKUP_ID = PRFL.WORKAREA_LKUP_ID)
			END AS WRKAREA_LKUP_TYPE,
			CASE
			WHEN PRFL.WORKAREA_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_VALUE
				FROM EQ.LOOKUP WRKLKUP
				WHERE WRKLKUP.LOOKUP_ID = PRFL.WORKAREA_LKUP_ID)
			END AS WRKAREA_LKUP_VALUE,
			CASE
			WHEN PRFL.WORKAREA_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT DESCR
				FROM EQ.LOOKUP WRKLKUP
				WHERE WRKLKUP.LOOKUP_ID = PRFL.WORKAREA_LKUP_ID)
			END AS WRKAREA_LKUP_DESCR,
			PRFL.FLAG_LICENSE_LKUP_ID,
			CASE
			WHEN PRFL.FLAG_LICENSE_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_NAME
				FROM EQ.LOOKUP LCNSLKUP
				WHERE LCNSLKUP.LOOKUP_ID = PRFL.FLAG_LICENSE_LKUP_ID)
			END AS LICENSE_LKUP_TYPE,
			CASE
			WHEN PRFL.FLAG_LICENSE_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_VALUE
				FROM EQ.LOOKUP LCNSLKUP
				WHERE LCNSLKUP.LOOKUP_ID = PRFL.FLAG_LICENSE_LKUP_ID)
			END AS LICENSE_LKUP_VALUE,
			CASE
			WHEN PRFL.FLAG_LICENSE_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT DESCR
				FROM EQ.LOOKUP LCNSLKUP
				WHERE LCNSLKUP.LOOKUP_ID = PRFL.FLAG_LICENSE_LKUP_ID)
			END AS LICENSE_LKUP_DESCR,
			PRFL.FLAG_CERTIFY_LKUP_ID,
			CASE
			WHEN PRFL.FLAG_CERTIFY_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_NAME
				FROM EQ.LOOKUP CERTLKUP
				WHERE CERTLKUP.LOOKUP_ID = PRFL.FLAG_CERTIFY_LKUP_ID)
			END AS CERT_LKUP_TYPE,
			CASE
			WHEN PRFL.FLAG_CERTIFY_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT FIELD_VALUE
				FROM EQ.LOOKUP CERTLKUP
				WHERE CERTLKUP.LOOKUP_ID = PRFL.FLAG_CERTIFY_LKUP_ID)
			END AS CERT_LKUP_VALUE,
			CASE
			WHEN PRFL.FLAG_CERTIFY_LKUP_ID IS NULL THEN ''
			ELSE
			(SELECT DESCR
				FROM EQ.LOOKUP CERTLKUP
				WHERE CERTLKUP.LOOKUP_ID = PRFL.FLAG_CERTIFY_LKUP_ID)
			END AS CERT_LKUP_DESCR,
			PRFL.PROFILE_ID,
			PRFL.ALT_EMAIL,
			PRFL.DATE_OF_BIRTH,
			PRFL.YEARS_OF_EXP,
			PRFL.ADDRESS1,
			PRFL.ADDRESS2,
			PRFL.CITY,
			PRFL.STATE,
			PRFL.COUNTRY,
			PRFL.ZIPCODE,
			PRFL.FLAG_PROFILE_INFO,
			PRFL.FLAG_EDUCATION,
			PRFL.FLAG_EMR,
			PRFL.FLAG_WRKEXP,
			PRFL.FLAG_REFERENCE,
			PRFL.FLAG_PROFILE_COMPLETE,
			PRFL.RESUME_AWS_KEY,
			PRFL.BG_LEGAL,
			PRFL.BG_DENIED,
			PRFL.BG_INVESTIGATION,
			PRFL.BG_DEFENDANT,
			PRFL.BG_TERMINATED,
			PRFL.BG_PERFORMANCE,
			PRFL.FLAG_LICENSE,
			PRFL.FLAG_CERTIFY,
			PRFL.FLAG_PREFERENCE
		FROM EQ.MYSHIFT_USER SHFTUSR
		LEFT JOIN EQ.PROFILE PRFL ON SHFTUSR.USER_ID = PRFL.USER_ID
			WHERE SHFTUSR.ISACTIVE = TRUE) N1 
	LEFT JOIN 
	(SELECT PSPLTY.USER_ID,
			STRING_AGG(SPLTY.PROFESSION_LKUP_ID::text,
				', ') AS SPCLTY_LKUPID_LIST,		 
			STRING_AGG(SPLTY.SPECIALTY_NAME::text,
				', ') AS SPCLTY_NAME_LIST,
			STRING_AGG(SPLTY.DESCR::text,
				', ') AS SPCLTY_DESCR_LIST
		FROM EQ.SPECIALTY SPLTY,
			EQ.PROF_SPECIALITY PSPLTY
		WHERE SPLTY.SPECIALTY_ID = PSPLTY.SPECIALTY_ID 
	 		GROUP  BY PSPLTY.USER_ID ) N2 ON N1.USER_ID = N2.USER_ID
	LEFT JOIN
	(SELECT PROFCERT.USER_ID,
			STRING_AGG(CERT.CERTIFICATE_ID::text,
				', ') AS CERT_ID_LIST,		 
			STRING_AGG(CERT.CERTIFICATE_NAME::text,
				', ') AS CERT_NAME_LIST,
			STRING_AGG(CERT.DESCR::text,
				', ') AS CERT_DESCR_LIST
		FROM EQ.CERTIFICATION CERT,
			EQ.PROF_CERTIFICATION PROFCERT
		WHERE CERT.CERTIFICATE_ID = PROFCERT.CERTIFICATE_ID
			GROUP  BY PROFCERT.USER_ID) N3 ON N1.USER_ID = N3.USER_ID
	LEFT JOIN
	(SELECT PROEDU.USER_ID,
			STRING_AGG(PROEDU.prof_education_id::text,
			', ') AS EDU_ID_LIST,
			STRING_AGG(PROEDU.DEGREE_NAME::text,
				', ') AS EDU_DEGREE_LIST,
			STRING_AGG(PROEDU.SCHOOL_NAME::text,
				', ') AS EDU_SCHL_LIST,
			STRING_AGG(PROEDU.CITY::text,
				', ') AS EDU_CITY_LIST,
			STRING_AGG(PROEDU.STATE::text,
				', ') AS EDU_STATE_LIST,
			STRING_AGG(PROEDU.ZIPCODE::text,
				', ') AS EDU_ZIP_LIST,
			STRING_AGG(PROEDU.START_DATE::text,
				', ') AS EDU_STRTDT_LIST,
			STRING_AGG(PROEDU.GRADUATION_DATE::text,
				', ') AS EDU_GRADDT_LIST,
			STRING_AGG(PROEDU.COUNTRY::text,
				', ') AS EDU_CNTRY_LIST
		FROM EQ.PROF_EDUCATION PROEDU
		GROUP  BY PROEDU.USER_ID) N4 ON N1.USER_ID = N4.USER_ID
	LEFT JOIN
	(SELECT PROEMR.USER_ID,
		STRING_AGG(PROEMR.EMR_LKUP_ID::text,
		', ') AS EMR_LKUPID_LIST,	 
		STRING_AGG(EMRLKUP.FIELD_NAME::text,
			', ') AS EMR_NAME_LIST,
		STRING_AGG(EMRLKUP.FIELD_VALUE::text,
			', ') AS EMR_VAL_LIST,
		STRING_AGG(EMRLKUP.DESCR::text,
			', ') AS EMR_DESCR_LIST
		FROM EQ.PROF_EMR PROEMR,
			EQ.LOOKUP EMRLKUP
		WHERE PROEMR.EMR_LKUP_ID = EMRLKUP.LOOKUP_ID
			GROUP  BY PROEMR.USER_ID) N5 ON N1.USER_ID = N5.USER_ID
	LEFT JOIN
	(SELECT PROFEXP.USER_ID,
			STRING_AGG(PROFEXP.START_DATE::text,
						', ') AS EXP_STRTDT_LIST,
			STRING_AGG(PROFEXP.END_DATE::text,
						', ') AS EXP_ENDDT_LIST,
			STRING_AGG(PROFEXP.POSITION_TITLE::text,
						', ') AS EXP_TITLE_LIST,
			STRING_AGG(PROFEXP.EMPL_TYPE_LKUP_ID::text,
						', ') AS EXP_EMPTYP_LIST,
			STRING_AGG(EMPTYPLKUP.FIELD_NAME::text,
				', ') AS EXP_EMPTYPNAME_LIST,
			STRING_AGG(EMPTYPLKUP.FIELD_VALUE::text,
				', ') AS EXP_EMPTYPVAL_LIST,
			STRING_AGG(EMPTYPLKUP.DESCR::text,
				', ') AS EXP_EMPTYPDESCR_LIST,							
			STRING_AGG(PROFEXP.FACILITY_NAME::text,
						', ') AS EXP_FCLTYNAME_LIST,
			STRING_AGG(PROFEXP.FACILITY_TYPE::text,
						', ') AS EXP_FCLTYTYP_LIST,
			STRING_AGG(PROFEXP.FACILITY_LOCATION::text,
						', ') AS EXP_FCLTYLOC_LIST,
			STRING_AGG(PROFEXP.UNIT::text,
						', ') AS EXP_FCLTYUNT_LIST,
			STRING_AGG(PROFEXP.PRIM_SPECIALTY::text,
						', ') AS EXP_FCLTYSPLTY_LIST,
			STRING_AGG(PROFEXP.CHARGE_EXP::text,
						', ') AS EXP_CHRG_LIST,
			STRING_AGG(PROFEXP.SHIFT_TYPE_LKUP_ID::text,
						', ') AS EXP_SHFTTYP_LIST,
			STRING_AGG(SHFTTYPLKUP.FIELD_NAME::text,
				', ') AS EXP_SHFTTYPNAME_LIST,
			STRING_AGG(SHFTTYPLKUP.FIELD_VALUE::text,
				', ') AS EXP_SHFTTYPVAL_LIST,
			STRING_AGG(SHFTTYPLKUP.DESCR::text,
				', ') AS EXP_SHFTTYPDESCR_LIST,				
			STRING_AGG(PROFEXP.ISCURRENT::text,
						', ') AS EXP_CURNTWRKNG_LIST,
			STRING_AGG(PROFEXP.HRS_PER_WEEK::text,
						', ') AS EXP_HRSWK_LIST,
			STRING_AGG(PROFEXP.FLOAT_SPECIALTY::text,
						', ') AS EXP_SPLTY_LIST,
			STRING_AGG(PROFEXP.SUPERVISOR::text,
						', ') AS EXP_SUPVR_LIST,
			STRING_AGG(PROFEXP.EXP_DESCR::text,
						', ') AS EXP_DESCR_LIST
			FROM EQ.PROF_EXPERIENCE PROFEXP,EQ.LOOKUP EMPTYPLKUP,EQ.LOOKUP SHFTTYPLKUP
			where PROFEXP.EMPL_TYPE_LKUP_ID = EMPTYPLKUP.LOOKUP_ID
			AND PROFEXP.EMPL_TYPE_LKUP_ID = SHFTTYPLKUP.LOOKUP_ID
			GROUP  BY PROFEXP.USER_ID) N6 ON N1.USER_ID = N6.USER_ID
	LEFT JOIN
	(SELECT JBTYP.USER_ID,
			STRING_AGG(JBTYP.JOBTYPE_LKUP_ID::text,
				', ') AS JBTYP_LKUPID_LIST,
			STRING_AGG(JBLKUP.FIELD_NAME::text,
				', ') AS JBTYP_NAME_LIST,
			STRING_AGG(JBLKUP.FIELD_VALUE::text,
				', ') AS JBTYP_VAL_LIST,
			STRING_AGG(JBLKUP.DESCR::text,
				', ') AS JBTYP_DESCR_LIST
			FROM EQ.PROF_JOBTYPE JBTYP,
				EQ.LOOKUP JBLKUP
			WHERE JBTYP.JOBTYPE_LKUP_ID = JBLKUP.LOOKUP_ID
			GROUP  BY JBTYP.USER_ID) N7 ON N1.USER_ID = N7.USER_ID
	LEFT JOIN
	(SELECT PROFLIC.USER_ID,
			STRING_AGG(PROFLIC.LICENSE_ID::text,
				', ') AS LICID_LST,
			STRING_AGG(PROFLIC.STATE::text,
				', ') AS LIC_ISSU_STAT_LST,
			STRING_AGG(PROFLIC.LICENSE_NUM::text,
				', ') AS LICNUM_LST,
			STRING_AGG(PROFLIC.EXPIRATION_DATE::text,
				', ') AS LICEXP_LST,
			STRING_AGG(PROFLIC.ISCOMPACT::text,
				', ') AS LIC_ISCOMPCT_LST,
			STRING_AGG(PROFLIC.LICENSE_AWS_KEY::text,
				', ') AS LICAWSKY_LST,
			STRING_AGG(PROFLIC.IS_VERIFIED::text,
				', ') AS LIC_VERFY_LST,
			STRING_AGG(LIC.PROFESSION_LKUP_ID::text,
				', ') AS LIC_LKUP_LST,
			STRING_AGG(LICLKUP.FIELD_NAME::text,
				', ') AS LIC_LKUP_NAME_LST,
			STRING_AGG(LICLKUP.FIELD_VALUE::text,
				', ') AS LIC_LKUP_VAL_LST,
			STRING_AGG(LICLKUP.DESCR::text,
				', ') AS LIC_LKUP_DESCR_LST,
			STRING_AGG(LIC.LICENSE_TYPE::text,
				', ') AS LIC_TYP_LST,
			STRING_AGG(LIC.DESCR::text,
				', ') AS LIC_DESCR_LST,
			STRING_AGG(LIC.ISACTIVE::text,
				', ') AS LIC_ACTV_LST
			FROM EQ.PROF_LICENSE PROFLIC,
				EQ.LICENSE LIC,
				EQ.LOOKUP LICLKUP
			WHERE PROFLIC.LICENSE_ID = LIC.LICENSE_ID
				AND LIC.PROFESSION_LKUP_ID = LICLKUP.LOOKUP_ID
			GROUP BY PROFLIC.USER_ID) N8 ON N1.USER_ID=N8.USER_ID
	LEFT JOIN
	(SELECT PROFONB.USER_ID,
			STRING_AGG(PROFONB.VACCINATION::text,
				', ') AS VACC_LST
			FROM EQ.PROF_ONBOARD PROFONB
			GROUP BY PROFONB.USER_ID) N9 ON N1.USER_ID=N9.USER_ID
	LEFT JOIN
	(SELECT PROFREF.USER_ID,
			STRING_AGG(PROFREF.REF_NAME::text,
				', ') AS REF_NAME_LST,
			STRING_AGG(PROFREF.REF_POSITION::text,
				', ') AS REF_POS_LST,
			STRING_AGG(PROFREF.REF_PHONE::text,
				', ') AS REF_PHN_LST,
			STRING_AGG(PROFREF.REF_EMAIL::text,
				', ') AS REF_EMAIL_LST,
			STRING_AGG(PROFREF.REF_RELATION::text,
				', ') AS REF_RLTN_LST,
			STRING_AGG(PROFREF.FACILITY_NAME::text,
				', ') AS REF_FCLTNAM_LST,
			STRING_AGG(PROFREF.START_DATE::text,
				', ') AS REF_STRTDT_LST,
			STRING_AGG(PROFREF.END_DATE::text,
				', ') AS REF_ENDDT_LST
			FROM EQ.PROF_REFERENCES PROFREF
			GROUP BY PROFREF.USER_ID) N10 ON N1.USER_ID=N10.USER_ID	
	LEFT JOIN
	(SELECT CNTDUR.USER_ID,
			STRING_AGG(CNTDUR.CNTRCTDUR_LKUP_ID::text,
				', ') AS CNTDUR_LKUPID_LST,
			STRING_AGG(CNTDUR_LKUP.FIELD_NAME::text,
				', ') AS CNTDUR_LKUPNM_LST,
			STRING_AGG(CNTDUR_LKUP.FIELD_VALUE::text,
				', ') AS CNTDUR_LKUPVAL_LST,
			STRING_AGG(CNTDUR_LKUP.DESCR::text,
				', ') AS CNTDUR_LKUPDESC_LST
			FROM EQ.PROFPREF_CNTRCT_DUR CNTDUR,
				EQ.LOOKUP CNTDUR_LKUP
			WHERE CNTDUR.CNTRCTDUR_LKUP_ID = CNTDUR_LKUP.LOOKUP_ID 
			GROUP  BY CNTDUR.USER_ID) N11 ON N1.USER_ID=N11.USER_ID	
	LEFT JOIN
	(SELECT SHFTSHD.USER_ID,
			STRING_AGG(SHFTSHD.SHIFT_SCHED_LKUP_ID::text,
				', ') AS SHFTSHD_LKUPID_LST,
			STRING_AGG(SHFTSHD_LKUP.FIELD_NAME::text,
				', ') AS SHFTSHD_LKUPNM_LST,
			STRING_AGG(SHFTSHD_LKUP.FIELD_VALUE::text,
				', ') AS SHFTSHD_LKUPVAL_LST,
			STRING_AGG(SHFTSHD_LKUP.DESCR::text,
				', ') AS SHFTSHD_LKUPDESC_LST
			FROM EQ.PROFPREF_SHIFT_SCHED SHFTSHD,
				EQ.LOOKUP SHFTSHD_LKUP
			WHERE SHFTSHD.SHIFT_SCHED_LKUP_ID = SHFTSHD_LKUP.LOOKUP_ID 
			GROUP  BY SHFTSHD.USER_ID) N12 ON N1.USER_ID=N12.USER_ID
	LEFT JOIN
	(SELECT SHFTTYP.USER_ID,
			STRING_AGG(SHFTTYP.SHIFTTYPE_LKUP_ID::text,
				', ') AS SHFTTYP_LKUPID_LST,
			STRING_AGG(SHFTTYP_LKUP.FIELD_NAME::text,
				', ') AS SHFTTYP_LKUPNM_LST,
			STRING_AGG(SHFTTYP_LKUP.FIELD_VALUE::text,
				', ') AS SHFTTYP_LKUPVAL_LST,
			STRING_AGG(SHFTTYP_LKUP.DESCR::text,
				', ') AS SHFTTYP_LKUPDESC_LST
			FROM EQ.PROFPREF_SHIFT_TYPE SHFTTYP,
				EQ.LOOKUP SHFTTYP_LKUP
			WHERE SHFTTYP.SHIFTTYPE_LKUP_ID = SHFTTYP_LKUP.LOOKUP_ID 
			GROUP  BY SHFTTYP.USER_ID) N13 ON N1.USER_ID=N13.USER_ID
	LEFT JOIN
	(SELECT WRKHRS.USER_ID,
			STRING_AGG(WRKHRS.WRKHRS_LKUP_ID::text,
				', ') AS WRKHRS_LKUPID_LST,
			STRING_AGG(WRKHRS_LKUP.FIELD_NAME::text,
				', ') AS WRKHRS_LKUPNM_LST,
			STRING_AGG(WRKHRS_LKUP.FIELD_VALUE::text,
				', ') AS WRKHRS_LKUPVAL_LST,
			STRING_AGG(WRKHRS_LKUP.DESCR::text,
				', ') AS WRKHRS_LKUPDESC_LST
			FROM EQ.PROFPREF_WRKHRS WRKHRS,
				EQ.LOOKUP WRKHRS_LKUP 
	 		WHERE WRKHRS.WRKHRS_LKUP_ID = WRKHRS_LKUP.LOOKUP_ID 
			GROUP  BY WRKHRS.USER_ID) N14 ON N1.USER_ID=N14.USER_ID			
WHERE N1.USER_ID in (139)