SELECT SHFTWRKD.SHIFT_WORKED_ID,
	SHFTWRKD.SHIFT_BYDATE_ID,
	SHFTBYDT.SHIFT_ID,
	SHFTWRKD.USER_ID,
	SHFTUSR.USER_NAME AS USER_NAME,
	SHFTWRKD.SEQ_NBR,
	SHFTWRKD.SHIFT_WORK_STATUS_LKUP_ID,
	WRKSTATLKUP.FIELD_NAME AS STATUS_LKUP_NAME,
	WRKSTATLKUP.FIELD_VALUE AS STATUS_LKUP_VALUE,
	WRKSTATLKUP.DESCR AS STATUS_DESCR,
	SHFTWRKD.CHECKIN_TIME,
	SHFTWRKD.CHECKOUT_TIME,
	SHFTWRKD.HRS_WORKED,
	SHFTWRKD.PAY_RATE,
	SHFTWRKD.PAY_FREQ_LKUP_ID,
	PYFRQLKUP.FIELD_NAME AS PAY_FREQ_LKUP_NAME,
	PYFRQLKUP.FIELD_VALUE AS PAY_FREQ_LKUP_VALUE,
	PYFRQLKUP.DESCR AS PAY_FREQ_DESCR,
	SHFTWRKD.PAY_AMOUNT,
	SHFTWRKD.PAY_STATUS_FLAG,
	SHFTWRKD.COMMENTS
FROM EQ.SHIFT_WORKED SHFTWRKD
LEFT JOIN EQ.SHIFT_BYDATE SHFTBYDT ON SHFTWRKD.SHIFT_BYDATE_ID = SHFTBYDT.SHIFT_BYDATE_ID
LEFT JOIN EQ.MYSHIFT_USER SHFTUSR ON SHFTWRKD.USER_ID = SHFTUSR.USER_ID
LEFT JOIN EQ.LOOKUP WRKSTATLKUP ON SHFTWRKD.SHIFT_WORK_STATUS_LKUP_ID = WRKSTATLKUP.LOOKUP_ID
LEFT JOIN EQ.LOOKUP PYFRQLKUP ON SHFTWRKD.PAY_FREQ_LKUP_ID = PYFRQLKUP.LOOKUP_ID